# Yusu Subdomain Docker Compose Konfiqurasiyası / Yusu Subdomain Docker Compose Configuration
# Bu fayl bütün servisləri orkestrasiya edir / This file orchestrates all services

version: '3.8'

services:
  # Nginx Reverse Proxy / Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: yusu-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # SSL sertifikatları üçün / For SSL certificates
    depends_on:
      - yusu-main
      - yusu-admin
      - yusu-seller
      - yusu-courier
    networks:
      - yusu-network
    restart: unless-stopped

  # Ana Müştəri Platforması / Main Customer Platform
  yusu-main:
    build:
      context: ./yusu-ecommerce
      dockerfile: Dockerfile
    container_name: yusu-main
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./dev.db
      - NEXTAUTH_SECRET=your-secret-key
      - NEXTAUTH_URL=http://yusu.com
    volumes:
      - ./yusu-ecommerce/prisma:/app/prisma
      - ./yusu-ecommerce/public:/app/public
    networks:
      - yusu-network
    restart: unless-stopped

  # Admin Paneli / Admin Panel
  yusu-admin:
    build:
      context: ./yusu-admin
      dockerfile: Dockerfile
    container_name: yusu-admin
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./dev.db
      - NEXTAUTH_SECRET=your-secret-key
      - NEXTAUTH_URL=http://admin.yusu.com
    volumes:
      - ./yusu-admin/prisma:/app/prisma
      - ./yusu-admin/public:/app/public
    networks:
      - yusu-network
    restart: unless-stopped

  # Seller Paneli / Seller Panel
  yusu-seller:
    build:
      context: ./yusu-seller
      dockerfile: Dockerfile
    container_name: yusu-seller
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./dev.db
      - NEXTAUTH_SECRET=your-secret-key
      - NEXTAUTH_URL=http://seller.yusu.com
    volumes:
      - ./yusu-seller/prisma:/app/prisma
      - ./yusu-seller/public:/app/public
    networks:
      - yusu-network
    restart: unless-stopped

  # Courier Paneli / Courier Panel
  yusu-courier:
    build:
      context: ./yusu-courier
      dockerfile: Dockerfile
    container_name: yusu-courier
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./dev.db
      - NEXTAUTH_SECRET=your-secret-key
      - NEXTAUTH_URL=http://courier.yusu.com
    volumes:
      - ./yusu-courier/prisma:/app/prisma
      - ./yusu-courier/public:/app/public
    networks:
      - yusu-network
    restart: unless-stopped

  # Veritabanı / Database
  database:
    image: postgres:15-alpine
    container_name: yusu-database
    environment:
      - POSTGRES_DB=yusu
      - POSTGRES_USER=yusu
      - POSTGRES_PASSWORD=yusu123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - yusu-network
    restart: unless-stopped

  # Redis Cache / Redis Cache
  redis:
    image: redis:7-alpine
    container_name: yusu-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - yusu-network
    restart: unless-stopped

networks:
  yusu-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
